URL=https://www.trello.com

AES=Please Don't ask me Okay

ValidUserID=vxs0570@mavs.uta.edu
InvalidUserID=test@test.com

ValidPassword=EKCSgMik+/QMMHtc4fc2Hg==
InvalidPassword=otgUrNB0zoUoQSI9ZpkbYA==


Cookies_Policy_Acceptance=/html/body/div[2]/div[2]/div/div[1]/div/div[2]/div/button[2]

Cookies_Policy_Atlassian=/html/body/div[1]/div[2]/div[1]/div/main/div/div/div[1]/div/div/div/div/div[2]/button[3]

Login_Link=/html/body/div[1]/header[1]/div/div[1]/div[2]/a[1]

Form_ID=form-login

#Login_Text_Box=/html/body/div[1]/div/div/div/div[2]/div/div/section/div[2]/form/div[1]/div[1]/div/div/input

Login_Text_Box=//*[@id="username"]

Login_Continue=/html/body/div[1]/div/div/div/div[2]/div/div/section/div[2]/form/button

Login_Password_Box=/html/body/div[1]/div/div/div/div[2]/div/div/section/div[2]/form/div[1]/div[2]/div/div/div/div/input

Login_Button=/html/body/div[1]/div/div/div/div[2]/div/div/section/div[2]/form/button

Skip_TwoFA=/html/body/div[1]/div/div/div/div[2]/div/div/section/div[2]/div[2]/button

#Login_Invalid_Mail_Msg=//*[@id="form-sign-up"]/div[2]/p

Login_Invalid_Mail_Msg=//*[@id="form-sign-up"]/div[2]/p/text()[1]

Login_Invalid_Password=/html/body/div[1]/div/div/div/div[2]/div/div/section/div[2]/div/section/div/div[2]/span/text()[1]

Create_Button=/html/body/div[1]/div[2]/div[1]/div/div/nav/div[1]/div/div[3]/button

Create_Board=gJDsPins_eYkBM
#nch-textfield__input lsOhPsHuxEMYEb lsOhPsHuxEMYEb VkPAAkbpkKnPst

Board_Title=input[data-testid='create-board-title-input']

Board_Create=//button[@data-testid='create-board-submit-button']
#/html/body/div[2]/div/section/div/form/button

Board_Select=[title='SE2 Assignment']
#board > div > button

Board_Options=/html/body/div[1]/div[2]/div[1]/div/main/div/nav/div[1]/div/div/div[2]/div/div[3]/ul/div[2]/li[1]/div[2]/div[1]/button/span/span

Board_Section=/html/body/div[2]/div/section

Close_Button_Option=#content > div > div > div.board-menu > div > section > div > ul > li:nth-child(21) > button

Close_Button=body > div.atlaskit-portal-container > div > section > div > button

Options_Icon=#content > div > div > div.board-main-content > div.board-header.u-clearfix.js-board-header > div > span.leC8WfkzmokiUl > button.GDunJzzgFqQY_3.frrHNIWnTojsww.bxgKMAm3lq5BpA.HAVwIqCeMHpVKh.SEj5vUdI3VvxDc
#/html/body/div[2]/div[2]/div[1]/div/main/div/nav/div[1]/div/div/div[2]/div/div[3]/ul/div[2]/li/div[2]/div[1]/button

Add_List=#board > div > button

List_TextBox1=#board > div.MwwP5nu2toWaoN > form > textarea

Add_List_Button=//button[@type='submit' and @data-testid='list-composer-add-list-button']

List_TextBox2=#board > div.MwwP5nu2toWaoN > form > textarea

Add_List_Button1=button[data-testid="list-composer-button"] span[data-testid="AddIcon"]

Delete_Board=#content > div > div > div.board-menu > div > section > div > ul > li:nth-child(16) > li > button

Delete_Board_Button=body > div.atlaskit-portal-container > div > section > div > button

Add_a_Card1=#board > li:nth-child(1) > div > div.IapUGb_Cq2VzSr > button.O9vivwyDxMqo3q.bxgKMAm3lq5BpA.iUcMblFAuq9LKn.PnEv2xIWy3eSui.SEj5vUdI3VvxDc

Add_a_Card2=#board > li:nth-child(2) > div > div.IapUGb_Cq2VzSr > button.O9vivwyDxMqo3q.bxgKMAm3lq5BpA.iUcMblFAuq9LKn.PnEv2xIWy3eSui.SEj5vUdI3VvxDc

List1=#board > li:nth-child(1)

List2=#board > li:nth-child(2)

List1_Add_a_Card_TextBox1=#board > li:nth-child(1) > div > ol > li > form > textarea

List1_Add_a_Card_TextBox2=#board > li:nth-child(1) > div > ol > li > form > textarea

List1_Card1=#board > li:nth-child(1) > div > ol > li:nth-child(1) > div > div > div.amUfYqLTZOvGsn > a

List1_Card2=#board > li:nth-child(1) > div > ol > li:nth-child(2) > div > div > div.amUfYqLTZOvGsn

List2_Add_a_Card_TextBox1=#board > li:nth-child(2) > div > ol > li > form > textarea

List2_Card1=/html/body/div[1]/div[2]/div[1]/div/main/div/div/div[2]/div/div/div[1]/div[2]/ol/li[2]/div/ol/li/div/div/div[1]/a

List2_Card2=/html/body/div[1]/div[2]/div[1]/div/main/div/div/div[2]/div/div/div[1]/div[2]/ol/li[2]/div/ol/li[2]/div/div/div[1]/a

List1_Card1_Label_Button=#layer-manager-card-back > div > div > div > div > div > div.P2jfHL0ryA_fCy > div.vasPIpPWWhzu4y > section:nth-child(1) > ul > div:nth-child(3) > li > button

Add_Label_SearchBox=/html/body/div[2]/div/section/div/div/div/input

Red_Label_CheckBox_Select=body > div.atlaskit-portal-container > div > section > div > div > ul > li:nth-child(4) > label

Red_Label_CheckBox=body > div.atlaskit-portal-container > div > section > div > div:nth-child(4) > ul > li > label

Filter_Button=#content > div > div > div.board-main-content > div.board-header.u-clearfix.js-board-header > div > span.leC8WfkzmokiUl > span.NiH9mJY3iVeTAl > button

Filter_SearchBox=body > div.atlaskit-portal-container > div > section > div > div:nth-child(2) > input

Filter_No_Members_CheckBox=body > div.atlaskit-portal-container > div > section > div > div:nth-child(4) > ul > li:nth-child(1) > label

Filter_With_Me_As_Members_CheckBox=body > div.atlaskit-portal-container > div > section > div > div:nth-child(4) > ul > li:nth-child(2) > label

Join_Me_As_Member=#layer-manager-card-back > div > div > div > div > div > div.P2jfHL0ryA_fCy > div.vasPIpPWWhzu4y > section:nth-child(1) > ul > li:nth-child(1) > button

Check_Filter1=/html/body/div[1]/div[2]/div[1]/div/main/div/div/div[2]/div/div/div[1]/div[2]/ol/li[1]/div/div[1]/p

Check_Filter2=/html/body/div[1]/div[2]/div[1]/div/main/div/div/div[2]/div/div/div[1]/div[2]/ol/li[2]/div/div[1]/p

Clear_All_Filters=#content > div > div > div.board-main-content > div.board-header.u-clearfix.js-board-header > div > span.leC8WfkzmokiUl > span.NiH9mJY3iVeTAl > button.rRs_e7MShvOFXM.frrHNIWnTojsww.DX_JGmmXEWu3Ti.bxgKMAm3lq5BpA.SEj5vUdI3VvxDc

Filter_Button1=#content > div > div > div.board-main-content > div.board-header.u-clearfix.js-board-header > div > span.leC8WfkzmokiUl > span.NiH9mJY3iVeTAl > button.bx61s1kHS9X4pV.dfzJI_PuP5CEVA.frrHNIWnTojsww.DX_JGmmXEWu3Ti.bxgKMAm3lq5BpA.SEj5vUdI3VvxDc

#Just_InCase=/html/body/div[1]/div[2]/div[1]/div/main/div/nav/div[1]/div/div/div[2]/div/div[3]/ul/div[2]/li[2]/a

Icon_Options=/html/body/div[1]/div[2]/div[1]/div/div/nav/div[2]/div[4]/button

Logout_Button=body > div.atlaskit-portal-container > div > section > div > div > div:nth-child(6) > nav > ul > li:nth-child(2) > button

LogOut_Button_Final=/html/body/div[1]/div/div/div/div[2]/div/div/section/form/div/button

Trello_Home_Button=/html/body/div[1]/div[2]/div[1]/div/div/nav/a

Close_Label_Button=body > div.atlaskit-portal-container > div > section > header > button

Close_List1_Card1=#layer-manager-card-back > div > div > div > div > button

Close_Filter=body > div.atlaskit-portal-container > div > section > header > button